### PR TITLE
add validation using assert sample and rtype

### PR DESCRIPTION
**Pull request by sbidari**
This PR aims to adds validation of `RandomVariables` using `_assert_sample_and_rtype` function. The validation methods currently implemented varies between checking something is a random variable using `isinstance` and checking that the random variable is valid (i.e check `tuple` return type). 

Based on the comments here https://github.com/CDCgov/multisignal-epi-inference/pull/341#issuecomment-2259357623, I think @damonbayer would like to keep the current implementation of `assert isinstance` and maybe add further check with `_assert_sample_and_rtype`? I wanted to confirm my understanding before adding more to this PR

### CODE REVIEW

**Comment by damonbayer** [comment]
I would like it so that any time we have some function `f(x: RandomVariable)`, we validate that `x` is a `RandomVariable` using `_assert_type`.

Separately, any time we instantiate a `RandomVariable`, we check that it is valid via something like `_assert_sample_and_rtype`.


So if you have code like this 

```python
my_non_rv = y
f(x=my_non_rv)
```
`f` will error because `x` is not a `RandomVariable`.

But if you have code like this
```python
my_rv = some_way_to_make_an_rv_with_the_wrong_return_type()
f(x=my_rv)
```
`some_way_to_make_an_rv_with_the_wrong_return_type` will error because it has the wrong return type and we won't even try to call `f`.

cc @dylanhmorris for thoughts.

**Comment by sbidari** [comment]
> I would like it so that any time we have some function `f(x: RandomVariable)`, we validate that `x` is a `RandomVariable` using `_assert_type`.

This can be done in #354 

> Separately, any time we instantiate a `RandomVariable`, we check that it is valid via something like `_assert_sample_and_rtype`.

I don't think `_assert_sample_and_rtype` is useful for this. But happy to hear if you have ideas for it.

I think this PR and associated issue can be closed? @damonbayer

**Comment by sbidari** [comment]
Note for clarification: shelving this for now after discussion with Damon. Potential design changes may affect this in the future.

**Comment by damonbayer** [comment]
> Note for clarification: shelving this for now after discussion with Damon. Potential design changes may affect this in the future.

Closing for now.

**Pull request closed without merging**
